import type { Metadata } from "next";
import localFont from "next/font/local";
import Navigation from "@/app/_components/Navigation";
import Logo from "@/app/_components/Logo";
import "@/app/_style/globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "The Wild Oasis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Logo />
          <Navigation />
        </header>
        <main className="container mx-auto px-4 py-8">{children}</main>
        <footer className="text-center py-4">
          <p className="text-sm text-gray-500">
            © {new Date().getFullYear()} The Wild Oasis. All rights reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
